coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
    patch:
      default:
        target: 70%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "examples/"
  - "setup.py"
  - "**/__init__.py"
  - "src/opendss_mcp/server.py"  # MCP server entry point, tested via integration
  - "src/opendss_mcp/data/download_official_feeders.py"  # Utility script

flags:
  unittests:
    paths:
      - src/opendss_mcp/
